### DISCUSSION TITLE
收集的吸血客户端IP及其配置

### DISCUSSION THREAD

**Discussion by rihalvnium76** [PBH-BTN/PeerBanHelper#55] [规则分享]
```yaml
  ip-address-blocker:
    enabled: true
    ips:
      - 1.171.51.0/24
      - 1.180.24.0/24
      - 1.180.25.0/24
      - 36.102.218.0/24
      - 59.47.225.0/24 # dt/torrent/v1
      - 59.47.237.0/24 # dt/torrent/v1
      - 110.187.213.0/24 # trafficConsume (devel) (anacrolix/torrent v1.53.2)
      - 112.45.16.0/24
      - 112.45.20.0/24
      - 112.192.189.0/24
      - 112.192.190.0/24 # github.com/thank243/trafficConsume (devel) (anacrolix/torrent v1.53.3)
      - 118.105.0.0/24
      - 122.224.33.0/24
      - 123.184.152.0/24
      - 146.70.134.0/24
      - 157.97.134.0/24
      - 218.7.138.0/24
      #- 220.88.111.208/24 # -UT360W- uTorrent 3.6.0.32
      - 221.11.96.0/24
      - 221.203.6.0/24
      - 240e:90e:2000::/48 # offline-download (devel) (anacrolix/torrent unknown)
```
