### DISCUSSION TITLE
v3.2.0

### DISCUSSION THREAD

**Discussion by Ghost-chu** [PBH-BTN/PeerBanHelper#77] [公告]
这是我们在迁移到 PBH-BTN 组织后的首个新版本，本版本重点更新了规则引擎和 WebUI。

###  JSON 规则引擎

原先的简易规则解析引擎升级为 JSON 规则引擎，所有已有的规则都将自动转换为 JSON 规则。  
新的规则引擎允许：
* 使用 if 字段嵌套另一个规则，作为开关控制此规则是否应该被执行
* 反转、更改规则的结果和行为
* 提供更细粒度的控制

示例：

```yaml
 client-name-blacklist:
    enabled: true
    banned-client-name:
      - '{"method":"STARTS_WITH","content":"-xl00"}'
      - '{"method":"CONTAINS","content":"xunlei"}'
      - '{"method":"STARTS_WITH","content":"taipei-torrent"}'
      - '{"method":"STARTS_WITH","content":"xfplay"}'
      - '{"method":"STARTS_WITH","content":"bitspirit"}'
      - '{"method":"CONTAINS","content":"flashget"}'
      - '{"method":"CONTAINS","content":"tudou"}'
      - '{"method":"CONTAINS","content":"torrentstorm"}'
      - '{"method":"CONTAINS","content":"qqdownload"}'
      - '{"method":"CONTAINS","content":"github.com/anacrolix/torrent"}'
      - '{"method":"STARTS_WITH","content":"qbittorrent/3.3.15"}'
      - '{"method":"STARTS_WITH","content":"dt/torrent"}'
      - '{"method":"STARTS_WITH","content":"dt"}'
      - '{"method":"STARTS_WITH","content":"go.torrent.dev"}'
      - '{"method":"STARTS_WITH","content":"github.com/thank423/trafficconsume"}'
      - '{"method":"STARTS_WITH","content":"taipei-torrent"}'
      - '{"method":"STARTS_WITH","content":"hp/torrent"}'
      - '{"method":"STARTS_WITH","content":"hp"}'
```

### 新版 WebUI

特别感谢由 @Gaojianli 和 @XiaoXice 构建的现代 WebUI，您可以在这里找到 PBH 的前端程序：[PBH-BTN/pbh-fe](https://github.com/PBH-BTN/pbh-fe)。新的 WebUI 包含现代界面、暗黑模式和手机端支持。

<img width="1280" alt="homepage" src="https://github.com/PBH-BTN/PeerBanHelper/assets/30802565/636784e5-6d0a-454b-b443-74e1558a2b23">
<img width="1280" alt="maxban" src="https://github.com/PBH-BTN/PeerBanHelper/assets/30802565/aee7280e-4a3a-48f0-bd99-6662f62dd3d2">
<img width="1280" alt="banlogs" src="https://github.com/PBH-BTN/PeerBanHelper/assets/30802565/d630f355-10b4-4798-88fb-4c707c24c9b2">
<img width="1280" alt="banlist" src="https://github.com/PBH-BTN/PeerBanHelper/assets/30802565/db018444-0e0c-4abd-9fc5-f0ac92815b4d">

### BTN-V2 协议

客户端的 BTN 协议已升级到 V2 版本（内部版本号：3），如果您正在使用 BTN 功能，请联系实例提供者获取新的 URL。  

## 优化

* 新增了 IP 解析缓存，降低执行规则匹配时因创建新的 IPAddress 实例导致的 CPU 时间的浪费
* 优化了部分模块检查规则引发的 CPU 尖峰

## 移除功能

* 移除了无人使用且存在法律风险的主动探测（Active Probing）模块

<hr /><em>This discussion was created from the release <a href='https://github.com/PBH-BTN/PeerBanHelper/releases/tag/v3.2.0'>v3.2.0</a>.</em>
