### ISSUE TITLE
考虑加入禁用在启动时强制检测geoip更新的配置项，或者延长超时时间

### ISSUE THREAD

**Issue by asky88** [PBH-BTN/PeerBanHelper#116]
中国大陆地区对maxmind.com 的访问并不稳定，需要通过浏览器下载mmdb文件放入data目录。但是程序“固执”地认为修改时间较久的mmdb文件无效。如果官方的mmdb也经常更新，那这样设计问题不大，但问题就是官方的更新时间也没有那么快。

**Comment by Ghost-chu** [comment]
```yaml
# Maxmind GeoIP/ASN 数据库
# https://www.maxmind.com/
# 在您填写相关密钥信息后，PBH 将自动下载所需的数据库文件，这视为您同意 Maxmind 的最终用户许可协议：https://www.maxmind.com/en/end-user-license-agreement
ip-database:
  # ==== 密钥信息开始 ==== - 在 LicenseKeys 页面创建凭据时，网页会提供这些信息
  account-id: ''
  license-key: ''
  # 允许自动更新 Maxmind GeoIP 数据库文件
  auto-update: true
  # ==== 密钥信息结束 ====
  # GeoIP-City 的数据库名称，默认使用免费版（GeoLite2-City），如果您购买了付费的数据库，可以自行替换
  database-city: 'GeoLite2-City'
  # GeoIP-City 的数据库名称，默认使用免费版（GeoLite2-ASN），如果您购买了付费的数据库，可以自行替换
  database-asn: 'GeoLite2-ASN'
```

请关闭 `auto-update` 选项
