### ISSUE TITLE
无法通过WebUI更新订阅（无法更新订阅？）

### ISSUE THREAD

**Issue by TTsdzb** [PBH-BTN/PeerBanHelper#180]
## 问题

在 WebUI 中的规则订阅里点击“更新全部”，服务端返回 500 内部错误。

同时，配置了自动检查间隔，但不论挂多久页面上都显示“最后更新：无”以及“规则数量：0”。终端也没有相关额外输出。

## 订阅配置

```yaml
  # 订阅规则
  ip-address-blocker-rules:
    enabled: true
    # 检查间隔
    # check-interval: 86400000 # 24小时检查一次 毫秒
    check-interval: 3600000 # 1小时检查一次 毫秒
    # 规则列表
    rules:
      # 规则ID（任意）
      0xde-0xad-0xbe-0xef:
        # 是否启用
        enabled: true
        # 显示名称
        name: 0xde-0xad-0xbe-0xef
        # 规则文件订阅地址
        url: https://raw.githubusercontent.com/PBH-BTN/BTN-Collected-Rules/main/0xde-0xad-0xbe-0xef.txt
      # 规则ID（任意）
      123pan:
        # 是否启用
        enabled: true
        # 显示名称
        name: 123pan
        # 规则文件订阅地址
        url: https://raw.githubusercontent.com/PBH-BTN/BTN-Collected-Rules/main/123pan.txt
      # 规则ID（任意）
      dt_torrent:
        # 是否启用
        enabled: true
        # 显示名称
        name: dt_torrent
        # 规则文件订阅地址
        url: https://raw.githubusercontent.com/PBH-BTN/BTN-Collected-Rules/main/dt_torrent.txt
      # 规则ID（任意）
      go_torrent:
        # 是否启用
        enabled: true
        # 显示名称
        name: go_torrent
        # 规则文件订阅地址
        url: https://raw.githubusercontent.com/PBH-BTN/BTN-Collected-Rules/main/go.torrent%20dev%2020181121.txt
      # 规则ID（任意）
      hp_torrent:
        # 是否启用
        enabled: true
        # 显示名称
        name: hp_torrent
        # 规则文件订阅地址
        url: https://raw.githubusercontent.com/PBH-BTN/BTN-Collected-Rules/main/hp_torrent.txt
      # 规则ID（任意）
      multi-dial:
        # 是否启用
        enabled: true
        # 显示名称
        name: multi-dial
        # 规则文件订阅地址
        url: https://raw.githubusercontent.com/PBH-BTN/BTN-Collected-Rules/main/multi-dial.txt
```

## 预期情况

WebAPI 返回非 5xx 值，并更新订阅或返回”请求错误”信息。

## 实际情况

返回 500，后台报错输出：

```
[10:31:54] [JettyServerThreadPool-Virtual-27/WARN]: 500 Internal Server Error
java.net.ConnectException: null
        at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1065) ~[java.net.http:?]
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:227) ~[java.net.http:?]
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:280) ~[java.net.http:?]
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(PlainHttpConnection.java:238) ~[java.net.http:?]
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.nio.channels.ClosedChannelException
        at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:204) ~[?:?]
        at java.base/sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:873) ~[?:?]
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:961) ~[?:?]
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:210) ~[java.net.http:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:212) ~[java.net.http:?]
        ... 9 more
```

## 其他信息

使用环境变量指定魔法：

```
all_proxy=http://127.0.0.1:7890/
http_proxy=http://127.0.0.1:7890/
https_proxy=http://127.0.0.1:7890/
ftp_proxy=http://127.0.0.1:7890/
```

其他程序可以正常访问：

![image](https://github.com/PBH-BTN/PeerBanHelper/assets/62687036/e0fef4ce-0df7-4688-b2cb-13b2bd11a7fd)
