### ISSUE TITLE
[bug] web 设置下载器不会保存到config里

### ISSUE THREAD

**Issue by jqtmviyu** [PBH-BTN/PeerBanHelper#202]
## 环境

* env: docker
* version: 4.3.0

## compose

```yaml
services:
  peerbanhelper:
    image: "ghostchu/peerbanhelper:4.3.0"
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ./data:/app/data
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "9898:9898"
```

## 截图

![image](https://github.com/PBH-BTN/PeerBanHelper/assets/19925192/4f9196c6-877c-403d-a4de-ed9b2b9e233d)
![image](https://github.com/PBH-BTN/PeerBanHelper/assets/19925192/f06f166f-3caa-4371-a92d-bb608e9e6007)

## 复现步骤

1. 正常启动容器
2. 删掉其他两个下载器, 只保留tr
3. 修改配置, 能看到成功连接上
4. 查看配置文件, 类型是qb
5. 重启容器就变成qb了, 再次修改类型回tr还是不会保存.
