### ISSUE TITLE
ipv6的多播检测机制是否应该放宽

### ISSUE THREAD

**Issue by Fvpder** [PBH-BTN/PeerBanHelper#206]
![image](https://github.com/PBH-BTN/PeerBanHelper/assets/107116491/21a0c118-2d0a-46bd-842b-e95a80f631c0)
![image](https://github.com/PBH-BTN/PeerBanHelper/assets/107116491/723a624d-4610-4d0a-af05-a62ea4f32aeb)
如果路由器启用了dhcpv6下发，windows的临时地址机制导致很容易存在三个甚至更多的ipv6地址，可能会导致误伤

**Comment by Ghost-chu** [comment]
PBH 版本是？

**Comment by Fvpder** [comment]
版本是4.3.1，平台是x64



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ghost_chu ***@***.***&gt;
发送时间: 2024年7月3日 00:11
收件人: PBH-BTN/PeerBanHelper ***@***.***&gt;
抄送: Fvpder ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PBH-BTN/PeerBanHelper] ipv6的多播检测机制是否应该放宽 (Issue #206)





 
PBH 版本是？

**Comment by Ghost-chu** [comment]
请尝试修改触发阈值：

```yaml

  # 多拨封禁（实验性功能）
  multi-dialing-blocker:
    enabled: true
    # 子网掩码长度
    # IP地址前多少位相同的视为同一个子网，位数越少范围越大，一般不需要修改
    subnet-mask-length: 24
    # 对于同小区IPv6地址应该取多少位掩码没有调查过，64位是不会误杀的保险值
    subnet-mask-v6-length: 64
    # 容许同一网段下载同一种子的IP数量，正整数
    # 防止DHCP重新分配IP、碰巧有同一小区的用户下载同一种子等导致的误判
    tolerate-num: 3 #<---------------------------需要修改的配置项
    # 缓存持续时间（秒）
    # 所有连接过的peer会记入缓存，DHCP服务会定期重新分配IP，缓存时间过长会导致误杀
    cache-lifespan: 86400
    # 是否追猎
    # 如果某IP已判定为多拨，无视缓存时间限制继续搜寻其同伙
    keep-hunting: true
    # 追猎持续时间（秒）
    # keep-hunting为true时有效，和cache-lifespan相似，对被猎杀IP的缓存持续时间
    keep-hunting-time: 2592000
```
