### ISSUE TITLE
[BUG] 设置代理之后无法通过 Hostname 以及私有 IP 连接到 Docker 中的 qBittorrent

### ISSUE THREAD

**Issue by IllyaTheHath** [PBH-BTN/PeerBanHelper#265]
### 版本号 - Version

v5.0.3

### 操作系统平台和系统架构 - OS  and CPU Arch

Debian Bookworm x64

### 部署方式 - Deploy method

Docker Compose

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

我的 qBittorrent 以及 PBH 都通过 Docker 部署，Proxy 是单独部署在另一台 Linux 机器上做的 TUN 网关，由于 Proxy 和二者不在同一个机器上，导致 PBH 通过 Docker Container hostname 以及 Docker Container IP 连接下载器时会失败。
通过分析发现是 PBH 会将内网 IP 也通过 Proxy 去连接，例如 http://10.5.0.2:8080，Proxy 识别到这是一个私有 IP 于是会不经过代理直接将流量转发到 10.5.0.2。 但由于我本地网络中并没有 10.5.0.2 这个 IP 所以会失败。通过 Hostname 连接同理。
我的 qBittorrent WebUI 套了正向 OpenID SSO 验证所以也无法通过外部域名或者 IP(192.168.2.x) 去连接。

### 复现步骤 - Reproduce steps

Docker Compose 文件如下：
```yaml
name: "downloader"
services:
  qbittorrentee:
    container_name: qbittorrentee
    image: superng6/qbittorrentee:4.6.4.10
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /srv/appdata/docker/data/qbittorrentee:/config
      - nas_downloads_bt:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    expose:
      - 8080
    networks:
      service-backend-v6:
      qbt-static-ip:
        ipv4_address: 10.5.0.2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M

  peerbanhelper:
    container_name: peerbanhelper
    image: ghostchu/peerbanhelper:v5.0.3
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /srv/appdata/docker/data/peerbanhelper:/app/data
    expose:
      - 9898
    networks:
      service-backend:
      service-backend-v6:
      qbt-static-ip:
        ipv4_address: 10.5.0.3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  service-backend-v6:
    name: service-backend-v6
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: fd80:0db8::/112
  qbt-static-ip:
    name: qbt-static-ip
    driver: bridge
    internal: true
    ipam:
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1
```

### 截图/日志文件 - Screenshot / Logs 

```
[02:55:27] [Ban Wave/INFO]: Checked 1 active torrents and 0 peers from 0 downloaders. Banned 0 peers and unbanned 0 expired bans (11ms)
[02:55:32] [/ERROR]: Failed to log in to qBittorrent Enhanced Edition (http://qbittorrentee:8080/api/v2), skipping...
```
```
[02:58:54] [Ban Wave/INFO]: Checked 1 active torrents and 0 peers from 0 downloaders. Banned 0 peers and unbanned 0 expired bans (10010ms)
[02:59:04] [/ERROR]: Failed to log in to qBittorrent_Enhanced_Edition (http://10.5.0.2:8080/api/v2), skipping...
```
![image](https://github.com/user-attachments/assets/369a3104-bf15-4d14-865a-d50a6ca4d455)

### 额外信息 - Addition Information

希望 PBH 能检测一下私有 IP，并使其不经过 Proxy。

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)
