### ISSUE TITLE
[BUG] 网络连接未经过已配置的 SOCKS5 代理服务器

### ISSUE THREAD

**Issue by cherinyy** [PBH-BTN/PeerBanHelper#266]
### 版本号 - Version

v5.0.4

### 操作系统平台和系统架构 - OS  and CPU Arch

Windows

### 部署方式 - Deploy method

Eclipse Temurin JDK 21 + jar

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

网络连接未经过已配置的 SOCKS5 代理服务器

### 复现步骤 - Reproduce steps

1. 配置 SOCKS5 代理服务器（socks5://localhost:7897/）
2. 配置 MaxMind 许可证密钥
3. 启动 PeerBanHelper

### 截图/日志文件 - Screenshot / Logs 

![image](https://github.com/user-attachments/assets/ea92903b-6653-44c2-af69-312dec55b1d0)

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
GeoCN (github.com/ljxi/GeoCN) 和 MaxMind 复用 HttpClient 下载数据，如果代理对 MaxMind 起效，那么也应对 GeoCN 起效。如果没有，请检查是否使用的是带有分流功能的代理软件。如果是，请检查 github.com 的分流规则。

**Comment by cherinyy** [comment]
> GeoCN (github.com/ljxi/GeoCN) 和 MaxMind 复用 HttpClient 下载数据，如果代理对 MaxMind 起效，那么也应对 GeoCN 起效。如果没有，请检查是否使用的是带有分流功能的代理软件。如果是，请检查 github.com 的分流规则。

跟软件无关，下载时并没有出现在软件的连接列表中。

**Comment by cherinyy** [comment]
在进一步测试后发现 PeerBanHelper 根本未连接 SOCKS5 代理服务器，正常连接 HTTP 代理服务器。

**Comment by cherinyy** [comment]
另外 `non-proxy-host` 配置疑似无效。

```
...
proxy:
  # 代理服务器设置
  # 注意：不支持需要密码验证的代理服务器
  # 0 = 不使用代理
  # 1 = 使用系统代理
  # 2 = 使用 HTTP(s) 代理
  # 3 = 使用 socks5 代理
  setting: 2
  # 代理服务器地址
  host: localhost
  # 代理服务器端口号
  port: 7897
  # 代理例外地址，使用 | 分隔不同条目
  non-proxy-host: 127.0.0.1|::1|localhost
...
```

![image](https://github.com/user-attachments/assets/ae7eac0a-873b-435e-b3d8-f0181894d3e8)
