### ISSUE TITLE
封禁日志清理

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#286]
在 config.yml 中有一个遗留的 persist.ban-logs-keep-days 选项，但它在 v5 ORM 重构后没有实现了。需要重新实现。

```yaml
# 数据持久化
persist:
  # 封禁日志保留天数
  ban-logs-keep-days: 180
```
