### ISSUE TITLE
[BUG] PBH 频繁向 stdout/stderr 输出无用日志

### ISSUE THREAD

**Issue by GalaxySnail** [PBH-BTN/PeerBanHelper#302]
### 版本号 - Version

v5.1.0

### 操作系统平台和系统架构 - OS  and CPU Arch

x86_64 GNU/Linux

### 部署方式 - Deploy method

Linux systemd

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

严格来说这不是一个 bug，但它是个不合理的行为。当使用 systemd 管理 PeerBanHelper 时，程序的 stdout/stderr 会被 systemd-journald 当作日志记录下来。而目前 PBH 默认会每隔 5 秒输出一条 `[Ban Wave/INFO]` 日志，大致如下：

```
[01:32:54] [Ban Wave/INFO]: 已检查 1 个下载器的 0 个活跃 Torrent 与 0 个 Peers。共封禁 0 个 Peers，并 解除 0 个过期的封禁 (8ms)
```

这样大量的无用日志淹没了真正有用的信息。

### 复现步骤 - Reproduce steps

直接启动 PBH 即可观察到

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
config.yml

```yaml
# 日志记录器配置
# Logger configurer
logger:
  # 是否隐藏 [完成] 已检查 XX 的 X 个活跃 Torrent 和 X 个对等体 的日志消息？
  # 在 DSM 的 ContainerManager 上有助于大幅度减少日志数量，并仅记录有价值的封禁等日志条目
  # Do you want hide [Completed] spam logs? Can be enabled on DSM to avoid too many logs.
  hide-finish-log: false
```
