### ISSUE TITLE
[BUG] Docker 版无法启动

### ISSUE THREAD

**Issue by lifegpc** [PBH-BTN/PeerBanHelper#487]
### 版本号 - Version

v6.2.2

### 操作系统平台和系统架构 - OS  and CPU Arch

Ubuntu 22.04 LTS amd64

### 部署方式 - Deploy methods

- [ ] Windows .exe 安装程序 (Windows .exe Installer)
- [ ] Windows .zip 绿色部署包 (Windows .zip Portable)
- [X] Docker
- [ ] JAR 包直接启动 (Start via .JAR directly)
- [ ] 群晖 DSM 套件 (Synology .spk package)
- [ ] Debian 软件包 (Debian .deb package)
- [ ] RedHat/Fedora 软件包 (RedHat/Fedora .rpm package)

### 添加的下载器 - Added Downloaders

- [X] qBittorrent
- [ ] BiglyBT/Azureus/Vuze
- [ ] Deluge
- [ ] Transmission

### 问题描述 - Issue Description

无法启动

### 复现步骤 - Reproduce steps

1. 从6.2.1版本升级到6.2.2
2. 无法启动

### 截图/日志文件 - Screenshot / Logs 

```
peerbanhelper  | Error: Could not find or load main class com.ghostchu.peerbanhelper.MainJumpLoader
peerbanhelper  | Caused by: java.lang.ClassNotFoundException: com.ghostchu.peerbanhelper.MainJumpLoader
```

### 额外信息 - Addition Information

直接降级 6.2.1 版本后可正常使用

docker-compose.yml 配置
```yaml
  peerbanhelper:
    image: ghostchu/peerbanhelper:v6.2.2
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ./peerban:/app/data
    ports:
      - 192.168.0.1:9898:9898
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
```

### 检查清单 - Check list

- [X] PeerBanHelper 已更新到最新版本 (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我已检查过 [PBH 文档](https://pbh-btn.github.io/pbh-docs/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://pbh-btn.github.io/pbh-docs/))
- [ ] 我没有检查这个检查清单，只是闭眼选中了所有的复选框，请关闭这个 Issue (I have not read these checkboxes and therefore I just ticked them all, Please close this issue)
- [X] 这不是一个安全漏洞，它可以被安全的公开报告。若需要报告安全漏洞，请[在此报告](https://github.com/PBH-BTN/PeerBanHelper/security/advisories/new) (This not a security related issue, can be safe report in public. If you want report a security exploit, please report it [here](https://github.com/PBH-BTN/PeerBanHelper/security/advisories/new))
