### ISSUE TITLE
[开发预览] 外部执行器 & BTN 网络 (2024/04/14)

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#50]
## 外部执行器

在我们开发 PBH 的过程中，我们注意到相当一部分的 BT 软件（如：uTorrent、BitComet、Aria2）并没有完善的 IP 封禁列表功能。为了能够兼容这些客户端，我们推出了 “外部执行器” 功能。  

目前外部执行器有两种：

* ipfilter.dat 执行器
  * 在 Banlist 发生更改时，会更新 `data/ipfilter.dat` 文件，以供其它 BT 客户端使用
* command-exec 执行器
  * command-exec 执行器能够在本机上执行一个或者多个系统命令，并在执行命令前，设置此命令进程的环境变量，并替换命令中的占位符，你可以用它来执行命令，设置系统防火墙，阻断IP地址

要在只读模式下兼容这些客户端，需要进行架构更改。此功能也在 v3 分支中逐步进行适配，也欢迎关注开发进度。

示例配置文件：

```yaml
# 封禁列表处理
# PBH 能够除了调用 BT 客户端的封禁 API 外，还能够进行如下操作，以便适配更多其它客户端
banlist-invoker:
  # 生成 ipfilter.dat 文件
  ipfilter-dat:
    enabled: true
  # 执行指定的系统命令
  # 所有的可用占位符都会被注册到执行的命令的进程环境变量中
  #如果您的命令没有读取环境变量的能力，则也可以使用 {%占位符名%}，这样 PBH 会在执行前替换命令中的占位符，但请注意转义问题
  # 可用占位符列表：
  #peer.ip - 对等体 IP 地址
  #peer.port - 对等体端口
  #meta.context - 封禁模块上下文
  #meta.description - 封禁描述
  #meta.banAt - 封禁时间
  #meta.unbanAt - 解封时间
  #meta.peer.id - PeerID
  #meta.peer.clientName - UserAgent 客户端名称字符串
  #meta.peer.uploaded - 总上传量
  #meta.peer.downloaded - 总下载量
  #meta.peer.progress - 客户端进度
  #meta.torrent.id - Torrent ID
  #meta.torrent.name - Torrent 名称
  #meta.torrent.hash - Torrent 的 Info Hash
  #meta.torrent.size - Torrent 大小
  command-exec:
    enabled: false
    reset:
      - "cmd /c echo reset!"
    ban:
      - "cmd /c echo ban!"
    unban:
      - "cmd /c echo unban!"
```

## BTN 网络

BTN 全名 Bittorrent Threat Network，是一个基于用户上报数据、根据信誉度生成规则的系统。用户通过 BTN 兼容客户端上报自己下载器上连接的 Peers 以及这些 Peers 的有关信息到 BTN 网络，BTN 可以根据这些信息分析哪些客户端明显异常。尽管更改 PeerID 和 Client Name 能够绕过单机检测，但这种小把戏无法欺骗更多的人。一旦数据汇总，便会出现明显异常（如：IP段下大量客户端，有大量下载但无上传，PeerID/UA 频繁更改等等）。

BTN 除了收集和汇总数据，也支持服务器规则下发。BTN 兼容客户端可以和 BTN 网络联系以更新自己的规则。

目前 BTN 正在活跃开发，一旦完成基本功能，BTN 将会以 MIT 协议开源。

示例配置文件：

```yaml
# BitTorrent Threat Network 威胁防护网络
btn:
  # 启用 BTN 模块
  enabled: true
  # 启用数据提交（匿名）
  # BTN 网络基于所有启用此功能的用户提交的数据，对 Peers 进行可信度验证
  # 通过启用此选项，您也会加入 BTN 网络并提交您的 Torrent 上的活动
  # 以下信息将被发送到 BTN 实例；
  # 您的 Torrent 列表（包括：Torrent 种子摘要的二次不可逆哈希和 Torrent 大小）
  # 连接到您的 Torrent 的所有 Peers （包括：IP地址、端口号、PeerID、UserAgent（ClientName），Peer协议，Peer总下载量，Peer总上传量，Peer瞬时上传速度，Peer瞬时下载速度，Peer下载进度，以及您的下载器名称）
  submit: true
  # 部分 BTN 实例可能要求您登录验证，如果是这样的话，您可在下面输入凭据信息
  app-id: "xxxxxxxxxxxxxxxxxxxx"
  app-secret: "xxxxxxxxxxxxxxxxxxx"
  # 填写实例 URL
  config-url: "https://xxxxxxxxxxx/ping/config"
```

如果您想要加入 BTN 网络测试，请加入 PBH QQ 讨论群。
