### ISSUE TITLE
[Other] ipfs节点是否连接成功缺少反馈，比如连上的节点ID

### ISSUE THREAD

**Issue by gsxgmpkt9020** [PBH-BTN/PeerBanHelper#914]
### 问题描述 - Issue Description

要使用 IPFS 功能，请启用此实验，并在配置文件中配置 Kubo IPFS 客户端的 RPC 地址。
启用后您将能够订阅其它人分享给您的位于 IPFS/IPNS 之上的 IP 规则。

```
# PeerBanHelper 去中心化网络服务 - Decentralized network service
# 请配置一个可用的 Kubo IPFS 节点 - Please configure an available Kubo IPFS node
decentralized:
  enabled: true
  # Kubo RPC MultiAddr
  kubo-rpc: /ip4/127.0.0.1/tcp/5001
  features:
    # 发布当前封禁列表到 IPFS 以允许它人订阅您的封禁列表内容，时间单位：毫秒，设置为 -1 以禁用
    # Publish current banlist to IPFS to allow others subscribe your banlist, time unit: milliseconds, set to -1 to disable
    publish-banlist: 3600000
```

一般都是本地的话，RPC应该就是默认值/ip4/127.0.0.1/tcp/5001

希望能有 ipfs节点连接成功的反馈输出，比如连上的节点ID

### 检查清单 - Check list

- [X] 这不是一个错误 （BUG） (This is not an bug/error)
- [X] PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)
- [X] 我已检查过 [PBH 文档](https://docs.pbh-btn.com/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://docs.pbh-btn.com/))
- [ ] 我没有检查这个检查清单，只是闭眼选中了所有的复选框，请关闭这个 Issue (I have not read these checkboxes and therefore I just ticked them all, Please close this issue)
- [X] 我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规、黑灰产、危害国家安全、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布了这些内容，我的账号将立刻从包括但不限于 PBH-BTN 组织、社交软件中封禁。所有主题、内容都将被立刻删除或折叠，撤销、删除和收回您所做出的一切贡献，并封禁 BTN 网络的中账号权限、排除您所提交的所有数据。在您违反相关规则时，PBH-BTN 将会将您的注册、登录、和最近访问的 IP 地址、电子邮件地址、以及其它可能追踪您或将您去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知的提供这些数据。 (I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as “taunting, name-calling, war-mongering, open-boxing (sometimes referred to as mansplaining), personal attacks, hatred, violence, insulting language, illegal activities, black and grey business, endangering national security, and committing or assisting others in committing telecommunication crimes”. I am aware that if I continue to post such content, my account will be immediately banned from organizations including but not limited to PBH-BTN, social software. All topics and content will be immediately deleted or collapsed, all contributions will be revoked, deleted and retracted, and you will be banned from the BTN network and all data you have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will delete your registration, login, and most recent IP address, email address, and any other information that may be used to track you or de-anonymize you from regular to permanent deletion, and will make this data available to the government, public security, or other relevant authorities without notice if they request it, no matter what country or region.)
